// Initialise the global array that allows the lookup of the depth of a given object
// GM2.0 does not have a depth on objects so on import from 1.x a global array is created
// NOTE: MacroExpansion is used to insert the array initialisation at import time
gml_pragma( "global", "__global_object_depths()");

// insert the generated arrays here
global.__objectDepths[0] = 0; // obj_gravestone
global.__objectDepths[1] = 0; // obj_entity_load
global.__objectDepths[2] = 0; // obj_camera
global.__objectDepths[3] = -100001; // obj_hitbox
global.__objectDepths[4] = 0; // obj_pl_spawner
global.__objectDepths[5] = 0; // obj_levelup
global.__objectDepths[6] = 0; // obj_plbulletpar
global.__objectDepths[7] = -100000; // obj_barrier
global.__objectDepths[8] = -100000; // obj_barrier_fade
global.__objectDepths[9] = 0; // obj_pl_staff_proj0
global.__objectDepths[10] = 0; // obj_pl_mage
global.__objectDepths[11] = 0; // obj_pl_hunter
global.__objectDepths[12] = 0; // obj_pl_mk
global.__objectDepths[13] = 0; // obj_wall_par
global.__objectDepths[14] = -1000000; // obj_wall0
global.__objectDepths[15] = -1000000; // obj_wall1
global.__objectDepths[16] = -1000000; // obj_wall2
global.__objectDepths[17] = 0; // obj_void
global.__objectDepths[18] = 0; // obj_portal_parent
global.__objectDepths[19] = 0; // obj_portal_exit
global.__objectDepths[20] = 0; // obj_portal_next
global.__objectDepths[21] = 0; // obj_portal_d0
global.__objectDepths[22] = 0; // obj_portal_d1
global.__objectDepths[23] = 0; // obj_lootbonustext
global.__objectDepths[24] = 0; // obj_bossbeattext
global.__objectDepths[25] = -99998; // obj_indicator
global.__objectDepths[26] = 0; // obj_floatingtext
global.__objectDepths[27] = -100000; // obj_debug
global.__objectDepths[28] = -10000; // obj_bulletclr_part
global.__objectDepths[29] = -1003; // obj_elec_part
global.__objectDepths[30] = 0; // obj_leg_sparkle_part
global.__objectDepths[31] = 0; // obj_heal_sparkle
global.__objectDepths[32] = 0; // obj_hol_part
global.__objectDepths[33] = 0; // obj_heal_part
global.__objectDepths[34] = 0; // obj_pixelbit
global.__objectDepths[35] = 0; // obj_pixelbit2
global.__objectDepths[36] = 0; // obj_poison_part
global.__objectDepths[37] = 0; // obj_bubble_part
global.__objectDepths[38] = 0; // obj_arcanerunes_part
global.__objectDepths[39] = 0; // obj_prep_part
global.__objectDepths[40] = 0; // obj_star_part
global.__objectDepths[41] = -90000; // obj_flash_fx
global.__objectDepths[42] = -90000; // obj_explosion_fx
global.__objectDepths[43] = -20000; // obj_thunder_fx
global.__objectDepths[44] = 0; // obj_dot_part
global.__objectDepths[45] = 0; // obj_dot_part2
global.__objectDepths[46] = 0; // obj_part_attup0
global.__objectDepths[47] = 0; // obj_part_dexup0
global.__objectDepths[48] = 0; // obj_part_spdup0
global.__objectDepths[49] = 0; // obj_part_burn0
global.__objectDepths[50] = 0; // obj_part_poison0
global.__objectDepths[51] = 0; // obj_part_chill0
global.__objectDepths[52] = 0; // obj_part_slow0
global.__objectDepths[53] = 0; // obj_part_confused0
global.__objectDepths[54] = -100000; // obj_inv
global.__objectDepths[55] = 0; // obj_container
global.__objectDepths[56] = 0; // obj_lootbag
global.__objectDepths[57] = 0; // obj_enemy_par
global.__objectDepths[58] = -10000; // obj_enemy_bullet_par
global.__objectDepths[59] = 0; // obj_skeleton
global.__objectDepths[60] = 0; // obj_skeletal_warrior
global.__objectDepths[61] = 0; // obj_skeletal_archer
global.__objectDepths[62] = 0; // obj_skeletal_firemage
global.__objectDepths[63] = 0; // obj_skeletal_frostmage
global.__objectDepths[64] = 0; // obj_abaghnid
global.__objectDepths[65] = -10000; // obj_enemy_bullet0
global.__objectDepths[66] = -10000; // obj_enemy_bullet1
global.__objectDepths[67] = -10000; // obj_enemy_bullet2
global.__objectDepths[68] = -120000; // obj_dgen
global.__objectDepths[69] = -120000; // obj_testing_gen
global.__objectDepths[70] = -120000; // obj_dgen_treasure
global.__objectDepths[71] = 0; // obj_dungeon0
global.__objectDepths[72] = 0; // obj_testing0
global.__objectDepths[73] = 0; // obj_dungeon1
global.__objectDepths[74] = 0; // obj_menu_control
global.__objectDepths[75] = -100100; // obj_credits
global.__objectDepths[76] = -110000; // obj_control
global.__objectDepths[77] = 0; // obj_log


global.__objectNames[0] = "obj_gravestone";
global.__objectNames[1] = "obj_entity_load";
global.__objectNames[2] = "obj_camera";
global.__objectNames[3] = "obj_hitbox";
global.__objectNames[4] = "obj_pl_spawner";
global.__objectNames[5] = "obj_levelup";
global.__objectNames[6] = "obj_plbulletpar";
global.__objectNames[7] = "obj_barrier";
global.__objectNames[8] = "obj_barrier_fade";
global.__objectNames[9] = "obj_pl_staff_proj0";
global.__objectNames[10] = "obj_pl_mage";
global.__objectNames[11] = "obj_pl_hunter";
global.__objectNames[12] = "obj_pl_mk";
global.__objectNames[13] = "obj_wall_par";
global.__objectNames[14] = "obj_wall0";
global.__objectNames[15] = "obj_wall1";
global.__objectNames[16] = "obj_wall2";
global.__objectNames[17] = "obj_void";
global.__objectNames[18] = "obj_portal_parent";
global.__objectNames[19] = "obj_portal_exit";
global.__objectNames[20] = "obj_portal_next";
global.__objectNames[21] = "obj_portal_d0";
global.__objectNames[22] = "obj_portal_d1";
global.__objectNames[23] = "obj_lootbonustext";
global.__objectNames[24] = "obj_bossbeattext";
global.__objectNames[25] = "obj_indicator";
global.__objectNames[26] = "obj_floatingtext";
global.__objectNames[27] = "obj_debug";
global.__objectNames[28] = "obj_bulletclr_part";
global.__objectNames[29] = "obj_elec_part";
global.__objectNames[30] = "obj_leg_sparkle_part";
global.__objectNames[31] = "obj_heal_sparkle";
global.__objectNames[32] = "obj_hol_part";
global.__objectNames[33] = "obj_heal_part";
global.__objectNames[34] = "obj_pixelbit";
global.__objectNames[35] = "obj_pixelbit2";
global.__objectNames[36] = "obj_poison_part";
global.__objectNames[37] = "obj_bubble_part";
global.__objectNames[38] = "obj_arcanerunes_part";
global.__objectNames[39] = "obj_prep_part";
global.__objectNames[40] = "obj_star_part";
global.__objectNames[41] = "obj_flash_fx";
global.__objectNames[42] = "obj_explosion_fx";
global.__objectNames[43] = "obj_thunder_fx";
global.__objectNames[44] = "obj_dot_part";
global.__objectNames[45] = "obj_dot_part2";
global.__objectNames[46] = "obj_part_attup0";
global.__objectNames[47] = "obj_part_dexup0";
global.__objectNames[48] = "obj_part_spdup0";
global.__objectNames[49] = "obj_part_burn0";
global.__objectNames[50] = "obj_part_poison0";
global.__objectNames[51] = "obj_part_chill0";
global.__objectNames[52] = "obj_part_slow0";
global.__objectNames[53] = "obj_part_confused0";
global.__objectNames[54] = "obj_inv";
global.__objectNames[55] = "obj_container";
global.__objectNames[56] = "obj_lootbag";
global.__objectNames[57] = "obj_enemy_par";
global.__objectNames[58] = "obj_enemy_bullet_par";
global.__objectNames[59] = "obj_skeleton";
global.__objectNames[60] = "obj_skeletal_warrior";
global.__objectNames[61] = "obj_skeletal_archer";
global.__objectNames[62] = "obj_skeletal_firemage";
global.__objectNames[63] = "obj_skeletal_frostmage";
global.__objectNames[64] = "obj_abaghnid";
global.__objectNames[65] = "obj_enemy_bullet0";
global.__objectNames[66] = "obj_enemy_bullet1";
global.__objectNames[67] = "obj_enemy_bullet2";
global.__objectNames[68] = "obj_dgen";
global.__objectNames[69] = "obj_testing_gen";
global.__objectNames[70] = "obj_dgen_treasure";
global.__objectNames[71] = "obj_dungeon0";
global.__objectNames[72] = "obj_testing0";
global.__objectNames[73] = "obj_dungeon1";
global.__objectNames[74] = "obj_menu_control";
global.__objectNames[75] = "obj_credits";
global.__objectNames[76] = "obj_control";
global.__objectNames[77] = "obj_log";


// create another array that has the correct entries
var len = array_length_1d(global.__objectDepths);
global.__objectID2Depth = [];
for( var i=0; i<len; ++i ) {
	var objID = asset_get_index( global.__objectNames[i] );
	if (objID >= 0) {
		global.__objectID2Depth[ objID ] = global.__objectDepths[i];
	} // end if
} // end for